# Use the official MySQL image as the base image
FROM mysql:latest

# Set the root password for the database (modify this to your desired password)
ENV MYSQL_ROOT_PASSWORD="admin1234"

# Create a new database and user
ENV MYSQL_DATABASE="melt_app_datbase"
ENV MYSQL_USER="root1"
ENV MYSQL_PASSWORD="admin1234"
